---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${K8S_SERVICE_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${K8S_SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_SERVICE_NAME}
    spec:
      hostAliases:
      - ip: "172.27.11.208"
        hostnames:
        - "ipa.bigdata.local"
      - ip: "172.27.11.227"
        hostnames:
        - "replicas-ipa.bigdata.local"
      containers:
      - name: ${K8S_SERVICE_NAME}
        image: bigdata-registry.local:5043/${JOB_NAME}:${BUILD_ID}-${BUILD_TIMESTAMP}-${GIT_COMMIT}
        ports:
        - containerPort: 9000
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: ${K8S_SERVICE_NAME}
  labels:
    app: ${K8S_SERVICE_NAME}
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: ${K8S_SERVICE_NAME}
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-${K8S_SERVICE_NAME}
spec:
  rules:
  - host: $K8S_SERVICE_NAME.bigdata.local
    http:
      paths:
      - path: /
        backend:
          serviceName: ${K8S_SERVICE_NAME}
          servicePort: 9000
---
